In [1]:
test = "Hello World"
print(test)

Hello World


In [2]:
import numpy as np

one_dimensional_arr = np.array([10, 12])
print(one_dimensional_arr)

[10 12]


In [6]:
b = np.arange(3)
b

array([0, 1, 2])

In [7]:
c = np.arange(1, 20, 3)
c

array([ 1,  4,  7, 10, 13, 16, 19])

In [8]:
lin_spaced_arr = np.linspace(0, 100, 5)
lin_spaced_arr

array([  0.,  25.,  50.,  75., 100.])

In [9]:
# reshape
one_dim_arr = np.array([1, 2, 3, 4, 5, 6])

# Multidimensional array using reshape()
multi_dim_arr = np.reshape(
                one_dim_arr, # the array to be reshaped
               (2,3) # dimensions of the new array
              )
# Print the new 2-D array with two rows and three columns
print(multi_dim_arr)

[[1 2 3]
 [4 5 6]]


In [11]:
print(multi_dim_arr.ndim)
print(multi_dim_arr.shape)
print(multi_dim_arr.size)

2
(2, 3)
6
