In [2]:
# pytorch
# deep learning

# gpu acceleration
# dynamic computations graphs
# intuitive interface for deep learning


# basics
# tensors
import torch

x = torch.tensor([1.0, 2.0, 3.0])
print('1D Tensor: \n', x)

1D Tensor: 
 tensor([1., 2., 3.])


In [3]:
y = torch.zeros((3,3))
print('2D Tensor: \n', y)

2D Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [4]:
# tensor []
# shape ()


# operations on tensors
a = torch.tensor([1.0, 2.0])
b = torch.tensor([3.0, 4.0])
# element-wise
print(a+b)

tensor([4., 6.])


In [7]:
# matrix multiplication
print(torch.matmul(a.view(2,1), b.view(1,2)))


tensor([[3., 4.],
        [6., 8.]])


In [8]:
# reshaping and transposing tensors
print(a)

tensor([1., 2.])


In [9]:
print(b)  # view doesn't change original form

tensor([3., 4.])


In [10]:
# reshaping and transposing tensors
t = torch.tensor([[1, 2, 3, 4],
                 [5, 6, 7, 8],
                 [9, 10, 11, 12]])

In [11]:
print(t.reshape(6,2))

tensor([[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8],
        [ 9, 10],
        [11, 12]])


In [12]:
print(t)

tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])


In [13]:
print(t.view(2,6))

tensor([[ 1,  2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11, 12]])


In [15]:
# transpose for dimensions
print(t.transpose(0,1))

tensor([[ 1,  5,  9],
        [ 2,  6, 10],
        [ 3,  7, 11],
        [ 4,  8, 12]])


In [19]:
# autograd and computational graphs
x = torch.tensor(2.0, requires_grad=True)
y = x**2
y.backward()

print(x)
print(x.grad)  
# put all derivatives into a vector
# gradient

tensor(2., requires_grad=True)
tensor(4.)


In [22]:
# building neural networks in pytorch
# nn.Linear(in_features, out_features)

# activation functions
# torch.relu, torch.sigmoid, torch.softmax

# forward
import torch.nn as nn
class NeuralNetwork(nn.Module):
    def __init__(self):
        super(NeuralNetwork, self).__init__()
        self.fc1 = nn.Linear(10,16)
        self.fc2 = nn.Linear(16,8)
        self.fc3 = nn.Linear(8,1)
    
    def forward(self,x):
        x = torch.relu(self.fc1(x))
        x = torch.relu(self.fc2(x))
        x = torch.sigmoid(self.fc3(x))
        
        return x

    
model = NeuralNetwork()
print(model)

NeuralNetwork(
  (fc1): Linear(in_features=10, out_features=16, bias=True)
  (fc2): Linear(in_features=16, out_features=8, bias=True)
  (fc3): Linear(in_features=8, out_features=1, bias=True)
)


In [32]:
# define loss function and optimizer
criterion = nn.BCELoss()
optimizer = torch.optim.Adam(model.parameters(), lr=0.01)

In [26]:
# train the model
inputs = torch.randn((100,10))
print(inputs.shape)

torch.Size([100, 10])


In [29]:
targets = torch.randint(0,2,(100,1)).float()
print(targets.shape)

torch.Size([100, 1])


In [35]:
epochs = 100

for epoch in range(epochs):
    optimizer.zero_grad() # reset gradients
    outputs = model(inputs) # forward pass
    
    loss = criterion(outputs, targets) # compute loss
    loss.backward() # compute gradients
    
    optimizer.step() # update weights
    
    if (epoch+1)%5==0:
        print(f"Epoch [{epoch+1}/{epochs}], Loss: {loss.item():.4f}")

Epoch [5/100], Loss: 0.0529
Epoch [10/100], Loss: 0.0335
Epoch [15/100], Loss: 0.0231
Epoch [20/100], Loss: 0.0162
Epoch [25/100], Loss: 0.0117
Epoch [30/100], Loss: 0.0089
Epoch [35/100], Loss: 0.0070
Epoch [40/100], Loss: 0.0057
Epoch [45/100], Loss: 0.0048
Epoch [50/100], Loss: 0.0041
Epoch [55/100], Loss: 0.0036
Epoch [60/100], Loss: 0.0032
Epoch [65/100], Loss: 0.0029
Epoch [70/100], Loss: 0.0026
Epoch [75/100], Loss: 0.0024
Epoch [80/100], Loss: 0.0022
Epoch [85/100], Loss: 0.0021
Epoch [90/100], Loss: 0.0019
Epoch [95/100], Loss: 0.0018
Epoch [100/100], Loss: 0.0017


## pytorch for beginners
## a fancy version

In [36]:
tensor1 = torch.tensor([1,2,3])
print(tensor1)

tensor([1, 2, 3])


In [38]:
tensor2 = torch.zeros(2,3)
print(tensor2)

tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [39]:
tensor3 = torch.rand(3,2)
print(tensor3)

tensor([[0.7641, 0.7003],
        [0.9347, 0.6130],
        [0.8731, 0.3791]])


In [41]:
# operations on tensor
# addition
# broadcasting
result_add = tensor1 + tensor2
print(result_add)

tensor([[1., 2., 3.],
        [1., 2., 3.]])


In [43]:
# multiplication
result_mul = tensor2 * 5
print(result_mul)

tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [45]:
# mtrix multiplication
result_matmul = torch.matmul(tensor2, tensor3)
print(result_matmul)

tensor([[0., 0.],
        [0., 0.]])
